apiVersion: v1
kind: ConfigMap
metadata:
  namespace: stackspin
  name: stackspin-velero-override
data:
  values.yaml: |
    configuration:
      #backupSyncPeriod: 1h
      #uploaderType: restic
      #fsBackupTimeout: "20h"
