apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatus
  namespace: stackspout
spec:
  releaseName: gatus
  chart:
    spec:
      # https://github.com/TwiN/helm-charts/blob/master/charts/gatus/Chart.yaml
      chart: gatus
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: gatus
        namespace: flux-system
  interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: stackspin-gatus-values
      optional: false
    - kind: ConfigMap
      name: stackspin-zulip-kustomization-variables
      optional: true
    # Allow overriding values by ConfigMap or Secret
    - kind: ConfigMap
      name: stackspin-gatus-override
      optional: true
    - kind: Secret
      name: stackspin-gatus-override
      optional: true
