apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: gatus-oauth-client
  # Has to live in the same namespace as the stackspin-gatus-oauth-variables secret
  namespace: flux-system
spec:
  grantTypes:
    - authorization_code
    - refresh_token
    - client_credentials
    - implicit
  responseTypes:
    - id_token
    - code
  scope: "openid profile email stackspin_roles"
  secretName: stackspin-gatus-oauth-variables
  redirectUris:
    - "https://${gatus_domain}/authorization-code/callback"
  #tokenEndpointAuthMethod: client_secret_post
