apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoiceninja-mariadb
  namespace: stackspout
  labels:
    stackspin.net/backupSet: "invoiceninja"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path
