apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  namespace: stackspout
  labels:
    stackspin.net/backupSet: "paperless"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
