apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-test-postgres
  namespace: stackspout
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
